using System.Collections.Generic;

namespace SP2.Definitions
{
    static class Secret
    {
        public static List<string> Answer1 = new List<string>
        {
            ".386",
            ".model flat,stdcall",
            "option casemap:none",
            @"include \masm32\include\windows.inc",
            @"include \masm32\macros\macros.asm",
            @"include \masm32\include\masm32.inc",
            @"include \masm32\include\user32.inc",
            @"include \masm32\include\kernel32.inc",
            @"includelib \masm32\lib\masm32.lib",
            @"includelib \masm32\lib\user32.lib",
            @"includelib \masm32\lib\kernel32.lib",
            ".data",
            "Cap db \"4-9-CSharp-IO-81-Ivanov\",0",
            "f PROTO",
            "main PROTO",
            ".code",
            "_start:",
            "invoke main",
            "invoke MessageBox,0,str$(eax),offset Cap,MB_OK",
            "ret",
            "f PROC",
            "push ebp",
            "mov ebp, esp",
            "sub ebp, 4",
            "mov eax, [ebp-4]",
            "push eax",
            "mov eax, 4",
            "mov ecx, eax",
            "pop eax",
            "add eax, ecx",
            "add ebp, 4",
            "mov esp, ebp",
            "pop ebp",
            "f ENDP",
            "main PROC",
            "push ebp",
            "mov ebp, esp",
            "sub ebp, 4",
            "mov eax, 5",
            "push eax",
            "call g",
            "mov [ebp-4], eax",
            "mov eax, [ebp-4]",
            "add ebp, 4",
            "mov esp, ebp",
            "pop ebp",
            "ret",
            "main ENDP",
            "END _start"
        };

        public static List<string> Answer2 = new List<string>
        {
            ".386",
            ".model flat,stdcall",
            "option casemap:none",
            @"include \masm32\include\windows.inc",
            @"include \masm32\macros\macros.asm",
            @"include \masm32\include\masm32.inc",
            @"include \masm32\include\user32.inc",
            @"include \masm32\include\kernel32.inc",
            @"includelib \masm32\lib\masm32.lib",
            @"includelib \masm32\lib\user32.lib",
            @"includelib \masm32\lib\kernel32.lib",
            ".data",
            "Cap db \"4-9-CSharp-IO-81-Ivanov\",0",
            "f PROTO",
            "main PROTO",
            ".code",
            "_start:",
            "invoke main",
            "invoke MessageBox,0,str$(eax),offset Cap,MB_OK",
            "ret",
            "g PROC",
            "push ebp",
            "mov ebp, esp",
            "mov eax, 10",
            "mov esp, ebp",
            "pop ebp",
            "g ENDP",
            "main PROC",
            "push ebp",
            "mov ebp, esp",
            "call g",
            "mov esp, ebp",
            "pop ebp",
            "ret",
            "main ENDP",
            "END _start"
        };
    }
}